.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/etc.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/refactoring.md

Feature : 기능 이슈
Bug : 버그 이슈
Refactoring : Refactoring 이슈
etc : etc 이슈 (애매한 것)

Api-docs : 이슈 템플릿 추가했습니다.

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/etc.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/refactoring.md

---
main에 추가된 issue 템플릿을 develop으로 merge 하겠습니다.
---
---

api-docs : main 브랜치에 issue 템플릿을 develop으로 merge 요청

---

backend/tos-proejct/build.gradle
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Admin.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Gender.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/resources/application.yml
backend/tos-proejct/src/test/java/com/togethersports/tosproejct/jdbcTest/MySQLTest.java

---
BE 작업을 위한 기본적인 도메인과 jdbc 연결을 구현했습니다.
---
디렉토리 생성 및 User 클래스 생성
---

Feature : jdbc 연결 및 user 도메인 생성

---

frontend/components/navigationBar.js
frontend/package-lock.json
frontend/package.json
frontend/pages/_app.js

---
기존 navBar 파일이 fast refresh가 작동하지 않는 문제가 있어서 수정하였습니다.
---
기존 파일을 대체하기 위해 navigationBar 로 변경하였고, flex 기반의 css로 변경하였으며,
반응형을 위해 media를 추가하였습니다.
(* 아직 해당 디자인 시안이 없어 작업은 하지 않았음)
---

Bugfix : 기존 navBar 파일의 HMR 오류 (hot refresh)

---

frontend/components/navigationBar.js
frontend/components/oAuth.js
frontend/package-lock.json
frontend/package.json
frontend/pages/_app.js
frontend/pages/api/auth/[...nextauth].js
frontend/pages/index.js

Google 로그인을 구현하고, 각종 UI 들을 수정하였습니다.
1. Google 로그인 구현
(* 현재는 Session으로 ID, Email, Name,Profile Image 를 가져오지만 Image는 쓰지 않음)
2. 각 Tag(Button)들의 Hover 기능 추가
3. 로그인 Session이 확인되면, 메인페이지로 이동하고 로그인 상태로 변경
4. 몇몇 UI들의 사이즈 별 깨짐 현상을 수정 함

Feature : Google Login 구현 및 각종 UI 개편 및 추가

---

frontend/components/authButton.js
frontend/components/oAuth.js
frontend/pages/_app.js
frontend/pages/api/auth/[...nextauth].js
frontend/pages/index.js

google Login 구현 및 로그인 완료 시 기능들 추가
구글 로그인을 구현하였습니다.
로그인과 로그아웃 시 메인페이지로 이동하도록 하였습니다.

Feature : google Login 구현 및 로그인 완료 시 기능들 추가

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/TestController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtTokenProvider.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Admin.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/MyInfoController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/test/java/com/togethersports/tosproejct/myInfomationTest/MyInformationTest.java

권한 설정 완료
User, Admin, Manager 권한 설정 기능 구현했습니다.

Feature: 권한 설정 완료

---

frontend/components/hotRoom.js
frontend/pages/index.js

React Hook으로 carousel 구현
1. 실시간 Hot한 방을 임시 더미데이터를 이용하여 구현
2. Carousel을 직접 react hook으로 구현하였음

Feature : 실시간 Hot한 방 React Hook으로 carousel 구현

---

frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js

회원가입 추가정보입력페이지 전체적인 css 수정 및 인적사항 페이지 프로필이미지 추가 구현
1. 회원가입 추가정보 입력페이지 전체적인 css 수정
2. 인적사항 페이지에 사용자의 프로필 이미지 추가 구현

Feature : 인적사항 프로필이미지 추가 구현 및 css 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/MyInfoController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/resources/application.yml

유저 정보 수정 구현
유저 정보를 수정하는 기능을 구현했습니다.
MyInfoController 메소드 추가, User 메소드 추가, UserService 메소드 추가 등등

Feature : 유저 정보 수정 구현

---

frontend/components/userInfoNavBar.js
frontend/pages/modification/interest.js
frontend/pages/signup/addinfo/interest.js

유저 정보 네비게이션 바 리팩토링
기존 유저 정보(개인정보, 관심종목, 활동지역) 네비게이션 바를 리팩토링하였습니다.
각 데이터들은 deactivation, activation 두 상태로 props를 통해 전달하여 작동합니다.

Feature : 유저 정보 네비게이션 바 리팩토링

---

frontend/pages/signup/addinfo/personalinfo.js

프로필 정보 받아오기 및 닉네임 중복확인 체크 구현
1. 프로필 사진 등록할 시, 보안상의 이유로 등록되는 fakepath 문제 해결
2. 백과의 통신을 위한 프로필 이미지 소스, 이미지 원본 이름, 확장자 변수에 담아놓기
3. 닉네임 중복확인 axios로 구현 (테스트 전)

Feature : 프로필 정보 받아오기 및 닉네임 중복확인 체크 구현

---

frontend/components/footer.js
frontend/package-lock.json
frontend/package.json
frontend/pages/index.js

footer UI
아직 완벽한 디자인이 나오진 않아 간단한 구성의 UI를 추가하였습니다.

Feature : 간단하게 footer UI 추가

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/TestController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/RefreshToken.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java

User-Agent에 따른 Refresh 토큰 발급 기능 구현
UserController, UserService, JwtService 메소드 수정

Feature : User-Agent에 따른 Refresh 저장 구현

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/ErrorResponse.java

Feature : cors 설정 완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/code/Code.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomAuthenticationEntryPoint.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/ErrorResponse.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Car.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java

Response 메세지 기능 구현
Response 메세지 기능 및 에러 메세지 구현

Feature: Response 메세지 기능 구현 #1

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomAuthenticationEntryPoint.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomSignatureException.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtTokenProvider.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/MyInfoController.java

BugFix : Message 처리 시, JWT 인증 무조건 통과 현상 해결

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/OtherInfoResponse.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/OtherInfoController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/OtherUserDTO.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java

다른 회원 정보 조회기능 구현했습니다.
에러처리 필요합니다.

Feature : 다른 회원 정보 조회 기능 구현

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Tag.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImage.java
backend/tos-proejct/src/main/java/etc/ActiveAreas.java
backend/tos-proejct/src/main/java/etc/Interests.java
backend/tos-proejct/src/test/java/com/togethersports/tosproejct/userCrudTest/JpaTest.java

Feature: Room도메인, 회원 활동 지역, 회원 관심 종목 구현완료

---

frontend/api/members.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/store/userRequestReducer.js

회원가입 axios 요청까지 최종 완료
1. 각 회원가입 정보 값들을 저장
2. 마지막 회원가입 요청 시 axios로 redux에 저장해 둔 데이터 값 전달

Function : 회원가입 axios 요청까지 최종 완료

---

frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js

인적사항 중복확인 수정 및 필수항목 표시구현
1. 인적사항 페이지에서 중복확인을 하지 않고 다음 버튼을 누를 시, alert 예외 처리 구현
2. addinfoNavBar 컴포넌트 각페이지에 추가
3. 인적사항 페이지 필수항목 부분은 (*) 표시 붙임

Feature : 인적사항 중복확인 수정 및 필수항목 표시구현

---

frontend/api/etc.js
frontend/api/members.js
frontend/api/rooms.js
frontend/components/navigationBar.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usercheck.js
frontend/pages/userlogin.js
frontend/store/rootReducer.js

axios 요청 관련 오타 및 버그 수정
1. 회원가입 로직에 해당하는 axios 요청들 수정

BugFix : axios 요청 관련 오타 및 버그 수정

---

frontend/api/members.js
frontend/components/tag.js
frontend/package-lock.json
frontend/package.json
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usercheck.js
frontend/store/rootReducer.js

회원가입 추가입력페이지 각종 수정 및 태그 생성
1. 태그 생성 (수정 필요)
2. 닉네임 최소 2글자 제한
3. 이미지 파일 오류 수정

Feature : 회원가입 추가입력페이지 각종 수정 및 태그 생성

---

frontend/api/etc.js
frontend/api/failResponse.js
frontend/pages/signup/addinfo/activearea.js
frontend/store/rootReducer.js

fail response 추가
1. fail response를 추가하여, 앞으로 accesstoken을 헤더에 담아 요청하는 모든 api에 편하게 사용가능.

Feature : fail response 추가

---

frontend/api/failResponse.js
frontend/components/navigationBar.js
frontend/pages/index.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/usercheck.js
frontend/pages/userlogin.js

fail response 현재까지 만든 모든 컴포넌트에 적용
fail response 현재까지 만든 모든 컴포넌트에 적용

Feature : fail response 현재까지 만든 모든 컴포넌트에 적용

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/code/Code.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/etc/ActiveAreas.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/etc/Interests.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomDefaultException.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/DefaultResponse.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageDTO.java

Get 파라미터 받기 수정, 기타 Response로직 수정
1. Get 요청 시, body값이 아닌 쿼리스트링(파라미터)로 요청 받도록 수정
2. Response로직 user값 리턴하는 부분 수정
3. Response시 로직에 따른 Response 코드 추가 및 Response추가

BugFix: Get 파라미터 받기 수정, 기타 Response로직 수정

---

frontend/api/etc.js
frontend/api/members.js
frontend/api/rooms.js
frontend/store/rootReducer.js

post, put axios 수정
1. axios 요청 post, put 부분 parameter 위치 변경으로 버그 수정

Bugfix : post, put axios 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Gender.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Provider.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/file/FileHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageDTO.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageService.java
backend/tos-proejct/src/test/java/com/togethersports/tosproejct/login/LoginTest.java

각종 에러를 수정했습니다.
1. 파일 path DB저장 추가
2. 파일 default 값 적용
3. 파일 디코딩 에러 수정
4. 파일 response 수정
5. 파일 service 로직 변경 및 리팩토링

BugFix : 각종 에러 수정#2

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/code/Code.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Tag.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/TokenResponse.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/controller/RoomCRUDController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/fields/RoomArea.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/fields/RoomImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/fields/RoomTag.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/module/RoomFileHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/repository/RoomRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/service/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/CustomUserDetailService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageDTO.java
backend/tos-proejct/src/main/java/etc/ActiveAreas.java
backend/tos-proejct/src/main/java/etc/Interests.java

Feature : Room Domain 구현

---

frontend/pages/signup/addinfo/personalinfo.js

프로필이미지 encode 오류 수정
1. 프로필 이미지 소스 encode 과정에서 백으로 전달했을 때 이미지 깨지는 오류 수정

Bugfix : 프로필이미지 encode 오류 수정

---

frontend/components/roomInfoNavBar.js

방 생성 페이지 상단 고정 메뉴들 구현
1. 방 생성하기 페이지에 있는 3가지의 고정된 메뉴들 컴포넌트 구현

Feature : 방 생성 페이지 상단 고정 메뉴들 구현

---

frontend/pages/signup/addinfo/interest.js
frontend/pages/usermodification.js

종목 예외처리 완료
1. 종목 선택 시 0개 또는 5개 초과인 경우 예외처리를 완료하였습니다.
*회원 수정 포함

Feature : 종목 예외처리 완료

---

frontend/pages/signup/addinfo/activearea.js

회원가입 활동지역 activeareas 배열 전역변수로 선언
1. 회원가입 활동지역 activeareas 배열 전역변수로 선언
1. 변경 전 redux에 활동지역이 안담기던 오류를 해결하고자 activeareas 배열 전역변수로 선언

Bugfix : 회원가입 활동지역 activeareas 배열 전역변수로 선언

---

frontend/pages/room/makeroom/roomsetting.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/store/rootReducer.js

방생성 기본정보설정 페이지 구현 완료
1. 방생성 기본정보설정 페이지 UI 구현
2. 방생성 기본정보설정 페이지 기능 구현
3. 각종 예외처리 구현
4. 리덕스에 데이터 담기, 방 생성관련 reducer 생성 구현

Feature : 방생성 기본정보설정 페이지 구현 완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtTokenProvider.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java

logout 구현
1. refresh 토큰 삭제 처리
2. 샹황에 따른 메세징 처리

Feature :  logout 구현

---

frontend/api/etc.js
frontend/api/members.js
frontend/api/rooms.js
frontend/components/navigationBar.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usercheck.js
frontend/pages/userlogin.js
frontend/pages/usermodification.js

API 수정된 명세에 맞게 수정
1. API 수정된 명세에 맞게 전체적으로 api 부분 수정
1. 응답 response에 status, content로 나눔
2. URL 패턴에 /api 추가

Feature : API 수정된 명세에 맞게 수정

---

frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js

방 생성 UI 수정
1. 디자인 수정안에 맞게 UI 수정

Feature : 방 생성 UI 수정 완료

---

frontend/components/banner.js
frontend/components/navigationBar.js
frontend/components/rooms.js/filter.js
frontend/components/rooms.js/filteredRooms.js
frontend/components/rooms.js/roomFilter.js
frontend/components/rooms.js/searchBar.js
frontend/components/rooms.js/selectExercise.js
frontend/pages/room/roomList.js

방 목록 UI 구성
1. 방 목록에 화면설계상 UI 구현은 했으나, 수정이 필요해보임.

Feature : 방 목록 UI 구성

---

frontend/pages/signup/addinfo/activearea.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

회원정보수정 생년월일 초기값 세팅완료
1. 회원정보수정 페이지 생년월일 초기값 세팅
2. 생년월일과 관련된 수정사안들 수정
3. 회원정보수정 페이지 초기값 세팅이 잘 됐는지 테스트 필요

Feature : 회원정보수정 생년월일 초기값 세팅완료

---

frontend/pages/oauth/saving.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/store/rootReducer.js

첫 로그인 유저 처리 및 회원정보 페이지 이전 버튼 추가
1. 첫 로그인 유저를 확인하여, 회원정보 추가페이지로 이동
2. 회원정보 페이지 이전 버튼 추가 + 예외처리 추가

Feature : 첫 로그인 유저 처리 및 회원정보 페이지 이전 버튼 추가

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/Account.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/AccountRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/JwtProperties.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/dto/TokenOfLogin.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/CustomOAuth2User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
backend/tos-proejct/src/main/resources/application-jwt.yml

* Refresh 생성, 발급, 저장
* AccessToken 갱신
* Refresh 토큰 생성
* Refresh 토큰 저장
* Access 토큰 갱신

Feature : Refresh 생성, 발급, 저장 #1

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/CommonCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/provider/JwtAuthenticationProvider.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java

Access Token refresh 작업
* refresh 를 통한 Access Token 재발급(갱신) 처리 완료
* JwtRefreshFilter 생성
* RefreshService 메소드 추가
* 기타 리팩토링

Feature : renew accessToken 작업완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/util/ClientIpUtils.java

Refresh 중복 방지 기능 구현 완료
* DB 테이블 User-Agent, Provider, Client Ip 추가

Feature : Refresh Token DB 중복 방지기능 구현완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java

Feature : Cors 세팅

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/code/CommonCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/CustomLogoutHandler.java

Logout 구현 완료
Logout Process 추가
* security config : 로그아웃 Handler 추가
* CustomLogoutHandler : 로그아웃 핸들러 추가

Feature : Logout 구현 완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/code/UserCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/CustomOAuth2User.java

닉네임 중복확인 구현완료
닉네임 중복확인 구현완료
* UserController : 닉네임 중복확인 관련 메소드 추가
* UserService : 닉네임 중복확인 관련 메소드 추가
* UserRepository : "existsByNickname" 메소드 추가

Feature : 닉네임 중복확인 구현완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java

Feature : 다른 회원 정보 조회 기틀 마련

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/area/ActiveArea.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/interest/Interest.java
backend/tos-proejct/src/main/resources/application.yml

Refactoring : 매핑 변경 및 로직 변경(ActiveArea, Interests)

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/code/UserCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/JwtErrorCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java

Feature : 다른 회원 정보 조회 및 리프레시 관련 예외 처리

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfModifyInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/exception/NicknameDuplicationException.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java

Feature : 회원 정보 수정 틀 마련

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/CustomLogoutHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java

Feature : 내 정보 조회, 로그아웃 리팩토링

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfInitInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfModifyInfo.java

내 정보 조회 수정
* 인자값 validation check 기능 추가

Feature : 내 정보 조회 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfoSummary.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java

nav바 요청 완료 및 다른 회원 정보 조회 로직 변경

Feature : nav바 요청 완료 및 다른 회원 정보 조회 로직 변경

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java

Feature : 사용자 권한 계층 구조 구현

---

frontend/api/members.js
frontend/components/login.js
frontend/components/navigationBar.js
frontend/components/roomInfoNavBar.js
frontend/components/userInfoNavBar.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

회원 파트 리팩토링 구현
1. 회원 파트에서 정리되지 않았던 className 들이나 여러 리팩토링 작업

Refactoring : 회원 파트 리팩토링 구현

---

frontend/api/failResponse.js

응답코드 수정
1. 회의에따라 수정된 응답코드에 맞게 수정

Refactoring : 응답코드 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/area/ActiveArea.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java

[Feature Request] Room Create ver1 완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/exception/NotFoundRoomException.java

방 조회 완료
방 조회 관련 로직 작업
* 조회 시, 방장일 경우 별도의 필드값 처리 필요
* 필드 변경에 따른 작업 필요

Feature : 방 조회 완료#1

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomCRUD.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfUpdate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagService.java

Feature : 방 수정 구현 완료#1

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfInitInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfModifyInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java

Login 과정 수정 및 추가정보 입력 과정 수정
* Login 과정 : 최초 로그인 시, "isFirst" 리턴 및 "informationRequired"리턴
* 추가정보 입력 과정 수정 : "추가 정보 입력" 기능과 "회원 정보 수정" 기능 통합

Feature: Login과정 수정 및 추가정보 입력 과정 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfUpdate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java

Feature : 기타 api 관련 로직 수정

---

frontend/api/members.js
frontend/components/calendar/calendar.js
frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/pages/oauth/saving.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/store/rootReducer.js

방 미참여 구현
1. 방 미참여 페이지 (모달) UI 구현
2. 데이터 주고받기 세팅 완료
3. 이미지 슬라이드 부분은 구현중 (50%)

Feature : 방 미참여 구현

---

frontend/components/imageSlide.js
frontend/components/modals/roomModal.js

이미지 슬라이드 구현
1. 이미지 슬라이드 컴포넌트화 구현 완료에 따라 방 미참여 모달 제작 완료

Feature : 이미지 슬라이드 구현

---

frontend/components/imageSlide.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/store/rootReducer.js

Refactoring : 회의 결과에 따른 수정 및 리팩토링

---

frontend/components/fixedRequestAlarm.js
frontend/components/fixedRoomAlarm.js
frontend/pages/room/roomlist.js

회원추가정보 및 방 생성 fixedAlarm 기능 완료
1. 회원추가정보 및 방 생성 fixedAlarm 기능을 완료했습니다.

Feature : 회원추가정보 및 방 생성 fixedAlarm 기능 완료

---

frontend/components/rooms/filter.js
frontend/components/rooms/searchBar.js
frontend/components/rooms/selectExercise.js
frontend/store/rootReducer.js

방 필터 기능 완료
1. 방 필터 기능 초기화 포함 완료

Feature : 방 필터 기능 완료

---

frontend/components/modals/roomModal.js
frontend/pages/signup/addinfo/personalinfo.js

Feature : 방 설명 페이지 조회수 구현

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/TosProjectApplication.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/auditing/RoomBaseEntity.java

Feature : Room Auditing 기능 추가

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java

방 정렬 기능 추가
* sort 메소드 추가
* "업뎃시간 순", "참가자 순", "시간 순" 구현 완료

Feature : 방 정렬 기능 추가

---

frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/components/rooms/filteredRooms.js

방 목록 데이터 수정 완료
1. 방 목록 데이터를 grid에 담고 클릭 시 상세 페이지 모달이 나오도록 하였습니다.

Feature : 방 목록 데이터 수정 완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
backend/tos-proejct/src/main/resources/application.yml

Feature : Tag 수정

---

frontend/components/modals/roomModal.js
frontend/pages/room/room.js

방 참가 페이지 UI 구현 완료
1. 방 참가 페이지 UI 구현
2. 방 설명 페이지(모달) 약간의 UI 수정

Feature : 방 참가 페이지 UI 구현 완료

---

frontend/components/modals/roomModal.js
frontend/components/rooms/participantList.js
frontend/pages/room/room.js

방 참여 페이지 데이터 세팅 완료
1. 방 참여 페이지에 데이터 세팅 완료
2. 참여자 리스트 컴포넌트화 완료
3. 방 설명 페이지에 host 필드 추가

Feature : 방 참여 페이지 데이터 세팅 완료

---

frontend/api/members.js
frontend/components/navigationBar.js
frontend/pages/myroom.js
frontend/pages/usermodification.js

회원정보 수정에 대한 수정사항과 데이터 반영 전 마이룸 수정
1. 회원정보 수정에 회원정보요청에 대한 API가 수정되었으나 반영되지 않았던 점을 수정
2. 변경 시 기존 유저의 정보가 변경되도록 수정
3. 마이룸의 방장, 참여한 방에 대한 데이터 호출 전 까지 구현

Feature : 회원정보 수정에 대한 수정사항과 데이터 반영 전 마이룸 수정

---

frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/createroom/roomtaginfo.js

방 수정페이지 리팩토링
1. 방 수정페이지 UI 오류 해결
2. 방 수정페이지 이미지 order 필드 추가
3. failResponse 방식 변경

Refactoring : 방 수정페이지 리팩토링

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryCustom.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfList.java

Feature : 방 수정사항 반영#2

---

frontend/components/rooms/participantList.js
frontend/pages/room/room.js

채팅 UI 구현 및 참여자목록 오류수정
1. 채팅 관련 자세한 UI 구현
2. 참여자목록에 생긴 조그마한 오류 수정

Feature : 채팅 UI 구현 및 참여자목록 오류수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/resources/application.yml

Feature : 이미지 기본 경로 변경 및 fetch 조인 적용

---

frontend/api/members.js
frontend/api/rooms.js
frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js

7차 스탠드업 테스트 버그 수정
1. 7차 스탠드업 테스트에서 문제가 생겼던 예외나 버그들을 수정하였습니다.

Feature : 7차 스탠드업 테스트 버그 수정

---

frontend/components/navigationBar.js
frontend/components/rooms/roomShowingBox.js

회원가입 성공 시 내 정보 렌더링 되게끔 변경
회원가입 성공 시 내 정보 렌더링 되게끔 변경

Feature : 회원가입 성공 시 내 정보 렌더링 되게끔 변경

---

frontend/api/failResponse.js
frontend/components/chatting.js
frontend/components/navigationBar.js
frontend/package-lock.json
frontend/package.json
frontend/pages/room/room.js

운동 대기방 페이지 채팅방 관련 UI 완성
1. 기존 채팅이 길 때, 스크롤이 맨 아래로 내려가 최신을 보여줍니다.
2. 내 채팅과 다른 사람 채팅을 구분해 UI를 배치하였습니다.
3. 스크롤을 커스텀하여 디자인을 변경하였습니다.

Feature : 운동 대기방 페이지 채팅방 관련 UI 완성

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/resources/application.yml
frontend/api/members.js
frontend/api/rooms.js
frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js

Reverts Cha-Young-Ho/TogetherSports#314

Revert "Feature : refactoring"

---

frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/createroom/roomtaginfo.js

방 수정 모달 크기 리팩토링
1. 방 수정 모달의 화면 크기마다 달라지는 요소들 크기 수정

Refactoring : 방 수정 모달 크기 리팩토링

---

backend/tos-proejct/build.gradle
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/auditing/ChatBaseEntity.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfPubRoom.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfReceiveRoom.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/SampleMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatPreHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SocketConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/resources/application.yml

Feature : 회의에 따른 수정사항 반영

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfParticipate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfOtherInfo.java

방 참가 요청 관련 구현 완료
*  방 참가 api 구현 완료
* "/api/room/{id}/user 관련 구현
1. 참여 관련 다대다 매핑 테이블 생성 필요
2. 관련 Repository, Service, 비즈니스 로직 구현 필요

Feature Request : 방 참가 요청 관련 구현 완료

---

frontend/components/chatting.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filteredRooms.js
frontend/package-lock.json
frontend/package.json
frontend/pages/index.js
frontend/pages/oauth/saving.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/store/rootReducer.js

채팅 및 회원정보 처리 관련 재수정
1. 소켓 연결, STOMP의 구독, 발행 시 token 추가
1. 회원정보의 정보를 받아오는 기존 행위를 변경하였습니다.

Feature : 채팅 및 회원정보 처리 관련 재수정

---

frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js

Refactoring : 회원정보추가입력 페이지 UI 개선

---

frontend/pages/room/createroom/roomschedule.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js

Refactoring : 방생성 페이지 UI 개선

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/participant/ParticipantService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
backend/tos-proejct/src/main/resources/application.yml

* 상세 조회 시, 요청자의 참여 여부에 따른 필드값 응답
* 참여 시
* "attendance":"true"
* 미참여 시
* "attendance":"false"

Feature : Attandance 구현

---

frontend/components/chatting.js
frontend/components/navigationBar.js
frontend/pages/oauth/saving.js

메시지 기능 완료
1. 좌, 우를 기준으로 내 메시지와 상대방 메시지를 구분하여 출력합니다.
2. 이전 대화를 기준으로 동일한 유저의 메시지라면 맨 아래 메시지에만 이미지를 나타나게 합니다.
3. STOMP에서 제시한 send(publish) 기능의 헤더는 바디와 같이 담을 수 없어 body에 객체로 추가하여 보내도록 수정하였습니다.
4. 이 외에 subscribe와 socket connect의 경우에는 헤더에 토큰을 담아 보내도록 하였습니다.

Feature : 메시지 기능 완료

---

frontend/components/navigationBar.js

NavBar UI 수정
1. UI 개선에 따른 NavBar UI 수정
2. 필요한 명세 후 로그인 유무에 따라 클릭 방지 구현 필요

Feature : NavBar UI 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/LocationController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/LocationDataInitializer.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/LocationRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/LocationService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/code/LocationCode.java

- 행정구역 API 추가 및 기능 수정
- 상위 행정구역이 없는 최상위 행정구역 조회 기능 추가
- URL 패턴의 명사 복수형으로 변경 (location -> locations)
- 서버 가동시 행정구역 데이터 생성 여부에 따라 초기화 작업 수행하도록 수정
X

Feature: 최상위 행정구역 API 구현 및 기타 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/location/LocationController.java

- 행정구역 API URL 패턴 수정
- /locations -> /api/locations

Fix: 행정구역 API URL 수정

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/SampleMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ApiError.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatErrorHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatPreHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ErrorCodeConstants.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SocketConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/participant/exception/NotParticipateRoomException.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/config/SecurityConfig.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
backend/tos-proejct/src/main/resources/application.yml

채팅 및 채팅 예외 구현
* 채팅 구현
* header의 Access Token에 따른 만료, 변조 예외 구현
* 채팅 구현
* 채팅 저장 구현

Feature : 채팅 및 채팅 예외 구현

---

frontend/api/rooms.js
frontend/components/modals/addAreaModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filter.js
frontend/components/rooms/filteredRooms.js
frontend/store/rootReducer.js

지역 추가 기능 완성
1. 지역 추가 기능을 완성하였습니다.
2. API 호출도 정상 작동 합니다.
3. 초기화도 정상 작동 합니다.

Feature : 지역 추가 기능 완성

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ClientMessage.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatErrorHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatPreHandler.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/participant/ParticipantService.java

채팅 과정 중 상황에 따른 예외 메세지 및 예외 처리 완료

Feature: 채팅 상황에 따른 예외 응답

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/DateTimeSortingUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepository.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfParticipate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomsOfMyRoom.java

myRoom api 구현 완료
1. 리팩토링
2. 주석 추가
3. Json 필드 명 변경에 따른 코드 수정

Feature : myRoom 기능 구현완료

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java

Feature : 클래스 및 메소드 주석 추가

---

frontend/api/rooms.js
frontend/components/chatting.js
frontend/components/navigationBar.js
frontend/pages/oauth/saving.js
frontend/store/rootReducer.js

유저 로그인 상태 관리 변경
1. 유저 로그인 상태 관리를 useState Hook으로 하였던 것을 좀 더 유연한 처리를 위해 Redux로 변경
2. 그로 인해 생기는 사소한 변경사항 수정

Feature : 유저 로그인 상태 관리 변경

---

backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/con.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/MessageOfLeave.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/MessageOfParticipate.java
backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/UserAndRoomOfService.java

Feature: Socket 및 방 관련 리팩토링

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryCustom.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/CountOfAvailableRoom.java

Feature : 참여할 수 있는 방 조회 구현 완료#1

---

frontend/components/main/banner.js
frontend/components/main/bannerRoomCount.js
frontend/components/main/main1.js
frontend/components/main/main2.js
frontend/components/main/useScrollCount.js
frontend/store/rootReducer.js

메인페이지 애니메이션 구현
1. 메인페이지 전체적인 UI 변경
2. 글자 및 그림에 fadeIn 애니메이션 적용
3. 이미지 받은 후 제대로 완성 필요

Feature : 메인페이지 애니메이션 구현

---

frontend/api/etc.js
frontend/api/members.js
frontend/api/rooms.js
frontend/components/chatting.js
frontend/pages/index.js
frontend/pages/oauth/saving.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js

몇몇 미활용 코드 정리 및 화면 강제이동 예외처리
1. 몇몇 미활용 코드 정리 및 화면 강제이동 예외처리

Feature : 몇몇 미활용 코드 정리 및 화면 강제이동 예외처리

---

frontend/api/failResponse.js
frontend/api/rooms.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filteredRooms.js
frontend/pages/room/room.js

테스트 중 오류코드 수정
1. 테스트 중 오류코드 수정

Feature : 테스트 중 오류코드 수정

---

frontend/api/rooms.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/createroom/roomtaginfo.js

이미지 관련 예외처리와 버그 수정
1. 이미지 null로 보낼 시 addOrder 예외 뜨는 것 처리
2. 이미지 설정 안돼있을 시, 기본이미지 설정
3. 방 설명 팝업 area 설정 제대로 안되는 것 해결

BugFix : 이미지 관련 예외처리와 버그 수정

---

frontend/components/chatting.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

room 동적 라우팅 변경
1. room 동적 라우팅 변경

Feature : room 동적 라우팅 변경

---

frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/participantList.js
frontend/pages/room/room.js

회원정보 팝업 UI 수정
1. 회원정보 팝업 UI 수정
2. 회원이 자신인지 아닌지에 따라 다른 프로필 팝업 UI 보이게 구현

Feature : 회원정보 팝업 UI 수정

---

frontend/api/failResponse.js
frontend/api/rooms.js
frontend/components/calendar/calendar.js
frontend/components/chatting.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

SSR으로 인한 렌더링 오류 수정
1. Calendar 컴포넌트 렌더 시 roomID 값이 없는 상태로 렌더되는 문제 수정
2. 테스트 중 생겼던 코드 누락 및 오류 수정

BugFix : 렌더링 오류 수정 및 오류 코드 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/controller/ExceptionControllerAdvice.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/auditing/RoomBaseEntity.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/code/RoomCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/AttendanceOfRoom.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfInfo.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfParticipate.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/UserAndRoomOfService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/config/SecurityConfig.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java

* json 필드 값 수정
* participates -> participants
* id -> roomId
* 로직 수정
*  attendance api 추가

Feature : 기타 로직 수정 및 json 필드 값 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfKickOut.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfLeave.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfParticipate.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java

- 메세지 관련 코드 수정
- 상황에 따른 메세지 생성
- 방 나가기
- 방 참여
- 방장 권한 위임
- 강퇴

Feature : 메세지 관련 코드 수정

---

frontend/api/rooms.js
frontend/components/chatting.js
frontend/components/modals/addAreaModal.js
frontend/components/rooms/filteredRooms.js
frontend/store/rootReducer.js

사라진 코드 및 오류 수정
1. 사라진 코드(reducer, chatting) 및 오류 수정

Feature : 사라진 코드 및 오류 수정

---

frontend/components/chatting.js
frontend/components/main/banner.js
frontend/components/modals/alarmModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/filter.js
frontend/components/rooms/searchBar.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomschedule.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js

테스트 후의 오류 해결 및 리팩토링
1. ImageSlide 에서 이미지 없을 시 나타나는 오류 해결 (<- 테스트 필요)
2. 예전에 구현해 놓은 alarmModal CSS 리팩토링
3. 여러 파일에 걸친 input, textarea의 focus 시 테두리 나타는거 없애기
4. 메인페이지 count 여러번 요청되는 오류 수정

BugFix : 테스트 후의 오류 해결 및 리팩토링

---

frontend/api/rooms.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

회원 프로필 팝업 오류 해결 및 방장 위임 , 유저 강퇴 기능 등록
1. 회원 프로필 팝업 파싱 오류 해결
2. 방장 위임 및 유저 강퇴와 관련된 API 등록 및 팝업에 해당 기능 등록

Feature : 회원 프로필 팝업 오류 해결 및 방장 위임 , 유저 강퇴 기능 등록

---

frontend/components/modals/userInfoModal.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

Feature : 방장 위임하기 구현

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/code/ChatCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/ChatOfPubRoom.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfKickOut.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/dto/UserOfOtherInfo.java

채팅 관련 로직 구현
상황에 따른 올바른 값 응답하도록 구현
* 예외 처리

Feature : 채팅 관련 로직 구현#2

---

frontend/components/modals/userInfoModal.js

Feature : 유저 강퇴하기 기능 구현

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/code/ChatCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/ChatOfHistory.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java

로깅 제거 및 주석 추가 및 리팩토링
* 메세지 포맷 수정
* 필요없는 로그 제거
* 주석 추가

Feature : 로깅 제거 및 주석 추가 및 리팩토링

---

frontend/components/chatting.js
frontend/pages/room/[roomId].js

채팅 추가 및 타입 분기 추가
1. 채팅 추가 및 타입 분기 추가

Feature : 채팅 추가 및 타입 분기 추가

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/code/ChatCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepository.java

Feature :  방 나가기

---

frontend/components/imageSlide.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/room/[roomId].js

방 수정 팝업 리팩토링 및 미흡한 부분 구현 완료
1. 방 수정 팝업 전체적인 리팩토링
2. 미흡했던 이미지 프리뷰 띄우는 기능 구현

Feature : 방 수정 팝업 리팩토링 및 미흡한 부분 구현 완료

---

frontend/components/modals/modifyRoomModal.js
frontend/pages/room/[roomId].js

테스트 후 리팩토링 작업
1. 운동 대기방 페이지 방 생성일시 내용 파싱 리팩토링
2. 방 수정 팝업 기존 태그들 세팅값 표시 안되는 오류 재해결

Refactoring : 테스트 후 리팩토링 작업

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatMessage.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/util/ParsingEntityUtils.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/Participant.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/ImageOfRoomInfo.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfInfo.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java

Refactoring : 리팩토링완료

---

frontend/api/rooms.js
frontend/components/Map.js
frontend/components/chatting.js
frontend/components/modals/addAreaModal.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filter.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/myroom.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

각종 오류 수정
1. 수정 맵의 동기문제 해결
2. 그 외 테스트 중 잘못된 값 수정

Feature : 각종 오류 수정

---

frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/components/rooms/floatingAlarm.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

WS 실시간 알림창 UI 구현
1. WS 실시간 알림창 UI 구현
2. imageSlide 오류해결

Feature : WS 실시간 알림창 UI 구현

---

frontend/components/chatting.js
frontend/components/rooms/floatingAlarm.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

Feature : WS 실시간 알림 구현

---

backend/tos-project/build.gradle
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/dto/UserOfModifyInfo.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomControllerTest.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomServiceTest.java

Feature : 방 업데이트 WS 전달 완료

---

backend/tos-project/build.gradle
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomStatus.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfParticipate.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomControllerTest.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomServiceTest.java

방 참가 Sevice부분 리팩토링 완료
service에서 Response를 응답하도록 수정

Feature : 방 참가 리팩토링

---

frontend/components/rooms/roomShowingBox.js
frontend/pages/myroom.js
frontend/store/rootReducer.js

마이룸 슬라이더 반응형 완성
1. 마이룸 슬라이더 반응형 완성

Feature : 마이룸 슬라이더 반응형 완성

---

backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/FieldsOfRoomList.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/Target.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomControllerTest.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomServiceTest.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/TestRoomUtils.java

Refactoring : 기타 리팩토링

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfCreate.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/handler/CustomLogoutHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/model/RefreshToken.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java

[BugFix]  방인원 버그 수정

---

frontend/components/chatting.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/modals/userInfoModal.js
frontend/components/rooms/participantList.js
frontend/pages/login.js
frontend/pages/myroom.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomschedule.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/room/roomlist.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

BugFix : 각종 오류 수정

---

frontend/api/failResponse.js
frontend/components/fixedRoomAlarm.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js
frontend/components/rooms/selectExercise.js
frontend/pages/_app.js
frontend/pages/index.js
frontend/pages/myroom.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/usermodification.js

토큰 관련 요청 시 이전 요청 이어서 하도록 수정
1. 토큰 관련 요청 시 이전 요청 이어서 하도록 수정

Feature : 토큰 관련 요청 시 이전 요청 이어서 하도록 수정

---

frontend/components/chatting.js
frontend/components/loading.js
frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/filteredRooms.js
frontend/pages/myroom.js

로딩 추가, 채팅 소켓 재연결 및 끊기 수정
1. 방 목록이나 마이룸 요청 시 방이 뜨기전 로딩화면 추가
2. 토큰 만료시 채팅 소켓 끊길 때 자동 재요청 및 하던 메시지

Feature : 로딩 추가, 채팅 소켓 재연결 및 끊기 수정

---

frontend/components/rooms/filteredRooms.js
frontend/pages/usermodification.js

방 목록 로딩 스크롤 형으로 수정
1. 방 목록 로딩 스크롤 형으로 수정

Feature : 방 목록 로딩 스크롤 형으로 수정

---

frontend/components/modals/modifyRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/modals/userInfoModal.js
frontend/components/rooms/floatingAlarm.js
frontend/components/rooms/participantList.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/activearea.js
frontend/store/rootReducer.js

BugFix : 오류 수정 및 이미지 리팩토링

---

frontend/api/failResponse.js
frontend/components/chatting.js
frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

소켓 오류 관련 수정
1. 소켓이 재연결될 때를 고려하여 수정
2. 재연결 시 이전 메시지를 이어하도록 수정(기존 동기오류로 빈 스트링만 가던 점 수정)
3. 수정하면서 관련된 잡다한 코드 수정

Feature : 소켓 오류 관련 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/mannerpoint/UserMannerPointService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/mannerpoint/dto/MannerPointOfPointing.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserController.java
frontend/components/chatting.js

매너지수 리팩토링
매너지수 서비스 리팩토링
매너지수 서비스 로직 변경

[Refactoring] 매너지수 리팩토링

---

backend/tos-project/src/main/java/com/togethersports/tosproject/location/Location.java
backend/tos-project/src/main/java/com/togethersports/tosproject/location/LocationDataInitializer.java

- 행정구역명과 지번주소 차이로 인한 api 기본 데이터 변경
- 행정구역 API 용 행정구역 데이터 최초 로딩 시 최상위 행정구역명 지번주소와 동일하게 변경
x

feat: 행정구역 API 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/TargetOfHostRequest.java

[Refactoring] 방장 권한 요청 DTO 클래스 명 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/area/ActiveArea.java

Refactoring : 활동 지역 Json Ignore 추가

---

frontend/components/modals/userInfoModal.js
frontend/components/rooms/floatingAlarm.js

BugFix : 알림창 및 매너지수 수정

---

frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/pages/room/[roomId].js

BugFix : navBar 프로필 오류 수정

---

frontend/api/failResponse.js
frontend/components/rooms/filter.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js
frontend/components/rooms/searchBar.js
frontend/pages/room/[roomId].js
frontend/pages/usermodification.js

수정사항 반영 완료
1. 무한스크롤링 쓰로틀링 추가
2. 방 제목 길어질 때 ... 처리
3. 룸 박스에 태그 길어지면 overflow하고 클릭시 다 표시
4. 필터 창 벗어나면 방 제목 초기화

bugfix : 수정사항 반영 완료

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfParticipate.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java

Feature : 테스트 후 기타 로직 수정

---

frontend/api/members.js
frontend/api/rooms.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/userInfoModal.js
frontend/pages/room/[roomId].js

테스트 후 오류 수정
1. 매너지수 재수정
2. 유저 강퇴 api 요청 변경
3. 특정 상황에서 방 수정 팝업의 tag 때문에 터지던 오류 수정

BugFix : 테스트 후 오류 수정

---

frontend/components/chatting.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/room/[roomId].js
frontend/pages/usermodification.js

유저 수정(닉네임)과 채팅 수정 완료
1. 채팅 닉네임과 시간 반영 완료
1. 정보 수정 닉네임 확인 로직 변경

Feature : 유저 수정(닉네임)과 채팅 수정 완료

---

frontend/api/etc.js
frontend/api/members.js
frontend/api/rooms.js
frontend/components/chatting.js
frontend/components/login.js

BugFix : endpoint 오류 수정

---

backend/tos-project/src/main/resources/application-security.yml

- aws 배포용 설정 변경
- application-security.yml 변경
x

choer: 백엔드 AWS 배포용 설정 파일 변경

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/JwtErrorCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/filter/JwtRefreshFilter.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/handler/JwtTokenRenewalExceptionHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java

Feature/backend/chayoungho/bug fix#5

---

frontend/api/failResponse.js
frontend/components/chatting.js
frontend/components/fixedRequestAlarm.js
frontend/components/fixedRoomAlarm.js
frontend/components/modals/alarmModal.js
frontend/components/modals/modifyRoomModal.js
frontend/components/navigationBar.js
frontend/components/roomInfoNavBar.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js
frontend/components/userInfoNavBar.js
frontend/pages/index.js
frontend/pages/myroom.js
frontend/pages/room/createroom/roomschedule.js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/room/createroom/roomtaginfo.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js

Feature : 일부 코드 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/mannerpoint/UserMannerPointService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/mannerpoint/code/MannerPointCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfList.java

이미지 로직 리팩토링
- Room Image 서비스 로직 수정
- User image 서비스 로직 수정

Refactoring : 이미지 로직 리팩토링

---

backend/tos-project/src/main/java/com/togethersports/tosproject/TosProjectApplication.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/model/GoogleUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/model/KakaoUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/model/NaverUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/model/OAuth2Provider.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/oauth2/model/OAuth2UserInfo.java
backend/tos-project/src/main/resources/application-aws.yml
backend/tos-project/src/main/resources/application-security.yml

- oauth2 로그인 시 오류 발생하는 부분 수정
- kakao 로그인 시 oauth2 인증키, 비밀키 오류 수정 (환경변수 변수명 오타)
- naver 로그인 시 null pointer exception 오류 수정 (nickname 필드 제거, 해당 필드는 사용되지 않음) 
x

Fix: oauth2 로그인 오류 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/security/annotation/CurrentUser.java

fix: CurrentUser 복원

---

backend/tos-project/src/main/resources/application-dev.yml
backend/tos-project/src/test/java/com/togethersports/tosproject/security/JwtServiceTest.java

Refactoring : 테스트 코드 작성

---

backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/resources/application-security-dev.yml

닉네임 중복 확인 로직 수정
작업 전 : 요청자의 닉네임을 받지 않음
작업 후 : 요청자의 닉네임을 받음

[Refactoring] 닉네임 중복 확인 로직 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/resources/application-security.yml
backend/tos-project/src/main/resources/application.yml

각종 로직 리팩토링 및 버그 수정
- 방 로직 수정
- 유저 로직 수정

[Refactoring & BugFix] 각종 로직 리팩토링 및 버그 수정

---

frontend/pages/room/createroom/roomschedule.js

방 생성 시 오늘 이전 날짜 클릭 방지
1. 방 생성 시 오늘 이전 날짜 클릭 방지

feature : 방 생성 시 오늘 이전 날짜 클릭 방지

---

frontend/api/failResponse.js
frontend/components/modals/addAreaModal.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/filter.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomtaginfo.js

발견된 이슈 수정
1. 검색 시 이전 필터 저장해두던 것 리롤(사용성 별로인 듯 해서)
2. 적용 시와 무한 스크롤링으로 요청하던 파라미터 값 오류 수정
3. 모달 스크롤 추가 및 검은화면 클릭시 종료로 변경

bugFix : 발견된 이슈 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/area/ActiveArea.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/auditing/ChatBaseEntity.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/MessageOfKickOut.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfCreated.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/resources/application-security.yml
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomControllerTest.java
backend/tos-project/src/test/java/com/togethersports/tosproject/room/RoomServiceTest.java

테스트 후 기타 수정사항 수정
- room Create DTO 생성
- 첫 사용자 닉네임 "익명" 처리

BugFix : 테스트 후 기타 수정사항 수정

---

frontend/components/modals/modifyRoomModal.js
frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/userInfoModal.js
frontend/pages/index.js
frontend/pages/room/[roomId].js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js

각종 아쉬운부분 리팩토링
1. 방 수정에 useState 변수 추가하여 변경된 값이 적용될 수 있게 함
2. 프로필 이미지 삭제 기능 구현
3. 메인페이지의 방 생성하기 버튼 막을 때, 페이지로 넘어가서 막았는데 페이지로 아예안넘어가게 하기
4. 방 삭제하기 기능은 잠시 보류
5. 회원 프로필 팝업의 닫기 버튼 위치 애매한거 조정

Refactoring : 각종 아쉬운부분 리팩토링

---

frontend/api/rooms.js
frontend/components/chatting.js
frontend/components/imageSlide.js
frontend/components/modals/roomModal.js
frontend/components/navigationBar.js
frontend/components/rooms/roomShowingBox.js

Feature : 발견된 이슈 5, 8, 10번 수정 완료

---

backend/tos-project/http-request/logout-test.http
backend/tos-project/src/main/java/com/togethersports/tosproject/security/config/SecurityConfig.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/handler/CustomLogoutHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/handler/CustomLogoutSuccessHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/matcher/LogoutRequestMatcher.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/repository/RefreshTokenRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/security/jwt/service/RefreshTokenService.java

- 로그아웃 버그 수정
- 로그아웃 핸들러 작성
- 로그아웃 요청시 리프레쉬 토큰 위치 변경
- 기존 요청 본문 json
- 변경 path variable

fix: 로그아웃 버그 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/TosProjectApplication.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/FileStorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/StorageService.java

- 특정 경로내 파일 삭제 기능 구현
- 특정 경로내 파일 불러오기 기능 구현 (base64 인코딩 문자열 반환)
- StorageService 인터페이스 기능 추가
x

feat: 파일 삭제, 불러오기 기능 구현

---

backend/tos-project/src/main/java/com/togethersports/tosproject/common/dto/FileOfImageSource.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/FileStorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/StorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/code/UserCode.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/dto/UserOfImageSource.java

- User image Source 조회 APi 구현
- UserController 메서드 추가
- UserService 메서드 추가
- Storage 인터페이스 및 구현체 메서드 추가(DTO 추가)

Feature : User image Source API 추가 구현#1

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomRepositoryImpl.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/auditing/RoomBaseEntity.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfInfo.java

Room Auditing의 수정시간 제거
* BaseEntity 의 "updatedTime" 삭제
* room QueryDsl(roomRepositoryImpl) 로직 수정
* room 생성자 수정

Refactoring : Room Auditing의 수정시간 제거

---

frontend/components/chatting.js

Feature : 채팅 api 수정

---

frontend/pages/room/[roomId].js
frontend/store/rootReducer.js

Feature : 방 수정 안내시간 필드 삭제

---

frontend/api/failResponse.js
frontend/api/members.js
frontend/api/rooms.js
frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

Feature : 이미지 소스 받아와서 이미지 수정 구현

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/FileStorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/resources/application.yml

- 유저 프로필 이미지 리팩토링
- UserService 로직 수정

[Refactoring] 유저 프로필 이미지 리팩토링

---

frontend/components/chatting.js
frontend/components/rooms/participantList.js
frontend/store/rootReducer.js

사용자 온 오프라인 상태 변경 수정
사용자 온 오프라인 상태 변경 수정

Feature : 사용자 온 오프라인 상태 변경 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/SystemMessageType.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/ChatOfOnOffline.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/OfflineOfUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/Participant.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/Status.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSession.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSessionRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSessionService.java

[Feature Request] 세션 일대다 매핑 완료

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/ClientMessage.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/OfflineOfUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/Status.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/dto/UserOfParticipantInfo.java
backend/tos-project/src/main/resources/application.yml

Feature : 온오프라인 구현 완료

---

frontend/components/main/main2.js
frontend/components/modals/createRoomModal.js
frontend/components/modals/signUpReqModal.js
frontend/components/navigationBar.js
frontend/pages/room/[roomId].js
frontend/pages/room/roomlist.js
frontend/pages/usermodification.js

Refactoring : 조회수 텍스트 및 메인페이지 로그인처리 구현

---

frontend/components/chatting.js
frontend/components/rooms/participantList.js

온 오프라인 시 참가자 목록 버그 수정
온 오프라인 시 참가자 목록 버그 수정

bugFix: 온 오프라인 시 참가자 목록 버그 수정

---

frontend/api/rooms.js
frontend/components/chatting.js
frontend/components/imageSlide.js
frontend/components/main/useScrollFadeIn.js
frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/participantList.js

Refactoring : 오타 및 간단한 수정사항들 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/FileStorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfList.java
backend/tos-project/src/main/resources/application.yml

Feature : 이미지 리팩토링#1

---

backend/tos-project/src/main/java/com/togethersports/tosproject/chat/ChatController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/dto/OnOfflineOfUser.java
backend/tos-project/src/main/java/com/togethersports/tosproject/chat/handler/ChatPreHandler.java
backend/tos-project/src/main/java/com/togethersports/tosproject/participant/ParticipantService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSession.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSessionRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/session/SocketSessionService.java

Feature : 주석 처리 및 리팩토링

---

frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/setRoomImages.js
frontend/pages/usermodification.js

Feature : 오류 수정 및 이미지 관련 초기화 버튼 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/common/controller/ExceptionControllerAdvice.java
backend/tos-project/src/main/java/com/togethersports/tosproject/common/file/service/FileStorageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImage.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/ImageOfRoomCRUD.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfUpdate.java
backend/tos-project/src/main/java/com/togethersports/tosproject/tag/TagService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java
backend/tos-project/src/main/resources/application-dev.yml
backend/tos-project/src/main/resources/application.yml

Feature/backend/chayoungho/room modify refactoring#1

---

frontend/api/members.js

로그아웃 API 엔드포인트 변경
1. 로그아웃 API 엔드포인트 변경

Fix : 로그아웃 API 엔드포인트 변경

---

frontend/api/failResponse.js
frontend/components/navigationBar.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/signup/addinfo/personalinfo.js

버그사항 수정
1. 추가 입력 시, 중복 확인 후 다른 닉네임으로 변경하면 넘어가던 것 수정
2. 닉네임이 중복된 상태로 추가 입력 시, "중복된 닉네임이 있습니다" 알림창을 =>  "중복된 닉네입입니다"로 수정
3. 추가 입력 시, "이전" 버튼에 경고사항 추가

Feature : 버그사항 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/image/dto/ImageProperties.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/ImageOfRoomCRUD.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserRepository.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java
backend/tos-project/src/main/resources/application.yml

방 기본 이미지 추가에 따른 리팩토링
- yml 수정
- room Image service 수정
- 기타 로직 수정

[Refactoring] 방 기본 이미지 추가에 따른 리팩토링

---

frontend/components/imageSlide.js
frontend/components/main/banner.js
frontend/components/modals/modifyRoomModal.js
frontend/pages/index.js
frontend/pages/signup/addinfo/activearea.js
frontend/pages/signup/addinfo/interest.js

오류 수정
1. 이미지 슬라이더 null 오류 수정
2. 방 수정 제목 변경사항 반영 안되던 것 수정
1. 회원 추가 정보 입력 멘트 변경

bugFix : 오류 수정 및 UI 변경

---

frontend/api/members.js
frontend/components/navigationBar.js
frontend/components/rooms/participantList.js

오류 수정
1. 로그아웃 API POST -> DELETE로 수정
2. 방 참여 페이지에서 나 자신이 가끔 오프라인으로 뜨던 것 수정

bugFix : 오류 수정

---

frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/room/[roomId].js
frontend/pages/room/createroom/roomsetting.js
frontend/pages/signup/addinfo/interest.js
frontend/pages/usermodification.js

Feature : 종목 관련 데이터명 변경

---

frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/selectExercise.js
frontend/pages/usermodification.js

exercise 영문으로 변경에 대한 요청사항 반영
1. exercise 영문으로 변경에 대한 요청사항 반영

Fix : exercise 영문으로 변경에 대한 요청사항 반영

---

backend/tos-project/src/main/java/com/togethersports/tosproject/room/dto/RoomOfInfo.java

Refactoring : 필요없는 필드 삭제

---

frontend/components/rooms/roomShowingBox.js

Fix : 코드 오타 수정

---

frontend/components/chatting.js
frontend/components/imageSlide.js
frontend/components/modals/navBarUserInfoModal.js
frontend/components/modals/userInfoModal.js
frontend/components/navigationBar.js
frontend/components/rooms/participantList.js
frontend/components/rooms/roomShowingBox.js

환경변수 API_ENDPOINT 추가
1. 환경변수 API_ENDPOINT 추가

Refactoring : 환경변수 API_ENDPOINT 추가

---

backend/tos-project/src/main/resources/application-aws.yml
backend/tos-project/src/main/resources/application-security.yml
backend/tos-project/src/main/resources/application.yml

feat: 주요 키 값 환경 변수화

---

backend/tos-project/src/main/java/com/togethersports/tosproject/image/dto/ImageProperties.java
backend/tos-project/src/main/resources/application-security.yml

fix: oauth2 redirect-uri 설정 변경

---

frontend/api/failResponse.js
frontend/api/rooms.js
frontend/components/navigationBar.js
frontend/components/rooms/filteredRooms.js
frontend/components/rooms/participantList.js

수정사항 반영
이미지 기본 바탕색 적절하게 변경 및 테스트용 값 안뺐던 것 수정

Fix : 수정사항 반영

---

backend/tos-project/src/main/java/com/togethersports/tosproject/area/ActiveArea.java
backend/tos-project/src/main/java/com/togethersports/tosproject/area/ActiveAreaService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomController.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/RoomService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/tag/TagService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/User.java
backend/tos-project/src/main/java/com/togethersports/tosproject/user/UserService.java

- 기존에 역단방향 매핑되어 있던 유저 활동 지역을 양정방향 매핑으로 바꾸었습니다.
- 매핑 변경에 따른 수정로직 또한 변경했습니다.
- userService 변경
- activeArea - User 엔티티 매핑 변경

Refactoring : 유저 활동 지역 양방향 매핑 및 수정 로직 변경

---

frontend/components/main/banner.js
frontend/pages/_app.js

Fix : 배너 크기 조정

---

frontend/components/imageSlide.js
frontend/components/main/banner.js
frontend/components/modals/roomModal.js

BugFix : 이미지 슬라이드 이미지 튀어나가는 오류 해결

---

frontend/components/chatting.js
frontend/components/modals/createRoomModal.js
frontend/components/modals/roomModal.js
frontend/components/rooms/filter.js
frontend/components/rooms/roomShowingBox.js
frontend/pages/_app.js
frontend/pages/myroom.js
frontend/pages/usermodification.js
frontend/store/rootReducer.js

LightHouse 성능 개선사항 반영 및 오류 수정
1. LightHouse 성능 개선사항 반영 및 오류 수정

Fix, Refactoring : LightHouse 성능 개선사항 반영 및 오류 수정

---

frontend/components/modals/userInfoModal.js
frontend/components/rooms/participantList.js
frontend/pages/_error.js
frontend/pages/room/[roomId].js

참여자 목록에서 내 정보 Modal 오류와 오류 페이지 수정
1. 참여자 목록에서 내 정보 Modal 오류와 오류 페이지 수정

bugFix : 발견된 오류 수정

---

frontend/api/failResponse.js
frontend/components/imageSlide.js
frontend/components/modals/modifyRoomModal.js
frontend/components/rooms/participantList.js
frontend/pages/404.js
frontend/pages/_error.js
frontend/pages/room/createroom/roomschedule.js
frontend/pages/signup/addinfo/personalinfo.js
frontend/pages/usermodification.js

BugFix : 이미지 및 글자 크기 오류 수정

---

backend/tos-project/src/main/java/com/togethersports/tosproject/image/RoomImageService.java
backend/tos-project/src/main/java/com/togethersports/tosproject/room/Room.java

- 룸 이미지 수정 시 ws로 roomImage가 null로 오는 오류 해결
- Room 엔티티 메소드 생성
- RoomImage Service 메소드 수정

BugFix : 룸 이미지 수정 시 ws로 roomImage가 null로 오는 오류 해결

---

frontend/components/chatting.js
frontend/components/rooms/participantList.js
frontend/components/rooms/roomShowingBox.js

Fix : 채팅 호출 오류와 채팅 프로필 이미지 크기 조절

---

backend/tos-project/src/main/resources/application.yml

feat: 파일 업로드 최대 사이즈 수정

---

frontend/components/imageSlide.js
frontend/components/modals/modifyRoomModal.js
frontend/components/modals/userInfoModal.js
frontend/pages/usermodification.js

테스트 후 이미지와 관련된 오류들 수정
1.  회원 프로필 수정에서 이미지 외의 다른 정보들 수정하면, 이미지가 무조건 기본이미지로 변경되는 오류 수정 
2. 방 수정 시, 인원수를 현재인원수보다 적지 않게 설정해야하는 것과 관련된 오류 수정
3. 참여자 목록에서 다른사람 정보조회때 내 정보가 담기는 오류 수정
4. 방 이미지 수정하고 나서 imageSlide의 이미지들이 최초에 한꺼번에 여러 이미지들이 뜨는 오류 수정

BugFix : 테스트 후 이미지와 관련된 오류들 수정

---

frontend/store/rootReducer.js

Reducer 초기값 오류 수정
Reducer 초기값 오류 수정

hotFix : Reducer 초기값 오류 수정

---

frontend/components/rooms/setRoomImages.js

hotFix : 방 수정 이미지 불러오기 시, 프리뷰 세팅 관련 오류 수정
